trigger:
- azure-pipelines

pool:
  vmImage: 'ubuntu-18.04'

steps:
- bash: |
    whoami
    pwd
    ls
    sudo apt-get update
    sudo apt-get install gcc-8 g++-8 gfortran-9
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
    sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-8 100
    gcc --version
    sudo apt-get install -qq openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-100 libhdf5-openmpi-dev python3 python3-pip libmetis-dev libparmetis-dev cxxtest
    sudo pip3 install --upgrade pip
    sudo pip3 install 'numpy>=1.12.0'
    #sudo pip3 install lxml
    #sudo pip3 install setuptools
    #sudo pip3 install sphinx
    #sudo pip3 install sphinx_rtd_theme

    git clone https://github.com/hfp/libxsmm
    cd libxsmm
    make generator -j2
    mkdir -p $HOME/bin
    cp bin/libxsmm_gemm_generator $HOME/bin
    export PATH=$HOME/bin:$PATH
    cd ..

    git submodule update --init
    # Compile dependencies
    
    # Impala
    cd submodules/ImpalaJIT
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_PREFIX=$HOME -- ..
    make -j4 install

    # yaml-cpp
    cd ../../yaml-cpp
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_PREFIX=$HOME -DYAML_CPP_BUILD_TOOLS=OFF -DYAML_CPP_BUILD_TESTS=OFF -- ..
    make -j4 install

    export CTEST_OUTPUT_ON_FAILURE=1
    cd ../../../
    mkdir build_cmake && cd build_cmake
    CMAKE_PREFIX_PATH=~:$CMAKE_PREFIX_PATH PKG_CONFIG_PATH=~/lib/pkgconfig/:$PKG_CONFIG_PATH cmake -DNETCDF=OFF -DMETIS=ON -DCOMMTHREAD=ON -DASAGI=OFF -DHDF5=ON -DCMAKE_BUILD_TYPE=Release -DTESTING=ON -DLOG_LEVEL=warning -DLOG_LEVEL_MASTER=info -DARCH=hsw -DPRECISION=double -DGEMM_TOOLS_LIST=LIBXSMM ..
    make -j4
    make test
